apiVersion: apps/v1
kind: Deployment
metadata:
  name: "storefront-{{ .Values.envt }}"
  labels:
    app: storefront
spec:
  replicas: "{{ .Values.replicaCount | default 1 }}"
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
    spec:
      containers:
        - name: storefront
          # Giả định tên image, bạn hãy cập nhật nếu khác
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default 'latest' }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy | default 'IfNotPresent' }}"
          ports:
            - containerPort: 8080
          env:
            # MicroProfile Config tự động map biến môi trường này vào @ConfigProperty(name = "order.service.base.url")
            # Code java tự thêm "http://", nên ở đây chỉ điền host:port
            - name: ORDER_SERVICE_BASE_URL
              value: "{{ .Values.orderServiceHost }}:{{ .Values.orderServicePort }}"
            - name: PRODUCT_SERVICE_BASE_URL
              value: "{{ .Values.productServiceHost }}:{{ .Values.productServicePort }}"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
