# Base URLs for backend services
# The client code will append specific paths like /items/{id} or /checkout/{id}
product.service.base.url=192.168.56.14:30200
order.service.base.url=192.168.56.14:30201
