apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: frontend-stg

images:
  - name: tantran0411/e-commerce-jsf
    newTag: gha-staging-master-c513a31
