apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml

namespace: frontend-stg

patches:
  - target:
      kind: Deployment
      name: storefront
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "order-service.ec-stg:8080"
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "product-service-svc.ec-stg:8080"
