name: Auto Build Front for STG
run-name: 'Build e-commerce-jsf and push image for Staging'

on:
  push:
    branches:
      - master
      - 'release/homelab/*'
    paths-ignore:
      - 'devops/**'
      - '.github/**'

concurrency:
  group: 'build-staging'
  cancel-in-progress: true

jobs:
  build:
    name: e-commerce-storefront-jsf
    uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/workflows/wc-reusable-auto-build-image.yml@develop/homelab/add-reuseable-build-image-workflow
    permissions:
      contents: write
    with:
      app_name: 'e-commerce-jsf'
      gha_environment: staging
    secrets: inherit
